### PR TITLE
Simplify build

### PR DESCRIPTION
**Pull request by Tristramg**
- don’t use templates anymore: generate valid rust file with constant
- commit that constant file
- compute at runtime some values

### CODE REVIEW

**Comment by Mubelotix** [comment]
Hello, thank you for your contribution! What's the benefit of committing the generated files?

**Comment by Tristramg** [comment]
It’s open to discussion. As it’s something that doesn’t change much over time (at least for the next hundred years) it would allow to notice changes if there is some fix (like the observatoire changes its predictions, or there was a bug somewhere).
If you prefer not to commit it, I’ll remove it

**Comment by Mubelotix** [comment]
> It’s open to discussion. As it’s something that doesn’t change much over time (at least for the next hundred years) it would allow to notice changes if there is some fix (like the observatoire changes its predictions, or there was a bug somewhere). If you prefer not to commit it, I’ll remove it

Yes please do. Either you commit them and disable the build script to speed up builds, either we keep the build script as it is and don't commit the generated files

**Comment by Tristramg** [comment]
I removed the generated file :)

(as a side note, in some projects it can be common to commit the generated files, typically the code generated for flatbuffers in order to have a functionning project on its own, and let the CI check the coherence).

**Pull request merged**
